YggdrasilWM: LayoutManager::Space Class Reference
LayoutManager::Space Class Reference
Space class This class represents a space in the layout. it's designed like a binary tree, with a parent, a right and a left child. Only leaf spaces have clients.
#include <LayoutManager.hpp>
Public Member Functions
Space (Point pos, Point size, int index, Space *parent=nullptr)
Construct a new Space object.
const Point & getPos () const
Get the position of the space.
void setPos (const Point &pos)
Set the position of the space.
const Point & getSize () const
Get the size of the space.
void setSize (const Point &size)
Set the size of the space.
int getSubspaceCount () const
Get the number of subspaces.
int getIndex () const
Get the index of the space.
void setIndex (int index)
Set the index of the space.
Space * getParent () const
Get the parent of the space.
void setParent (Space *parent)
Set the parent of the space.
const std::unique_ptr< Space > & getRight () const
Get the right child of the space.
void setRight (std::unique_ptr< Space > right)
Set the right child of the space.
const std::unique_ptr< Space > & getLeft () const
Get the left child of the space.
void setLeft (std::unique_ptr< Space > left)
Set the left child of the space.
Client * getClient () const
Get the client of the space.
void setClient (Client *client)
Set the client of the space.
void incSubSpaceCount ()
Increment the number of subspaces.
Private Attributes
Point pos_
Point size_
int index_
int subspace_count_
Space * parent_
std::unique_ptr< Space > right_
std::unique_ptr< Space > left_
Client * client_ {}
Detailed Description
Space class This class represents a space in the layout. it's designed like a binary tree, with a parent, a right and a left child. Only leaf spaces have clients.
Constructor & Destructor Documentation
Space()
LayoutManager::Space::Space (LayoutManager::Point pos, LayoutManager::Point size, int index, LayoutManager::Space * parent = nullptr)
Construct a new Space object.
Parameters
pos
size
index
parent
                                                        :
            pos_(pos),
            size_(size),
            index_(index),
            subspace_count_(1),
            parent_(parent),
            left_(nullptr),
            right_(nullptr){}
Member Function Documentation
getClient()
Client * LayoutManager::Space::getClient () const
Get the client of the space.
Returns
{ return client_; }
Referenced by TreeLayoutManager::addClientRecursive(), TreeLayoutManager::findSpaceRecursive(), TreeLayoutManager::growSpaceX(), TreeLayoutManager::removeClientRecursive(), and TreeLayoutManager::splitSpace().
getIndex()
int LayoutManager::Space::getIndex () const
Get the index of the space.
Returns
{ return index_; }
getLeft()
const std::unique_ptr< Space > & LayoutManager::Space::getLeft () const
Get the left child of the space.
Returns
{ return left_; }
Referenced by TreeLayoutManager::addClientRecursive(), TreeLayoutManager::findSpaceRecursive(), TreeLayoutManager::growSpaceX(), and TreeLayoutManager::removeClientRecursive().
getParent()
Space * LayoutManager::Space::getParent () const
Get the parent of the space.
Returns
{ return parent_; }
Referenced by TreeLayoutManager::growSpaceX(), TreeLayoutManager::removeClientRecursive(), and TreeLayoutManager::splitSpace().
getPos()
const Point LayoutManager::Space::getPos () const
Get the position of the space.
{ return pos_; }
Referenced by TreeLayoutManager::placeClientInSpace(), and TreeLayoutManager::splitSpace().
getRight()
const std::unique_ptr< Space > & LayoutManager::Space::getRight () const
Get the right child of the space.
Returns
{ return right_; }
Referenced by TreeLayoutManager::addClientRecursive(), TreeLayoutManager::findSpaceRecursive(), TreeLayoutManager::growSpaceX(), and TreeLayoutManager::removeClientRecursive().
getSize()
const Point LayoutManager::Space::getSize () const
Get the size of the space.
Returns
{ return size_; }
Referenced by TreeLayoutManager::addClientRecursive(), TreeLayoutManager::growSpaceX(), TreeLayoutManager::placeClientInSpace(), and TreeLayoutManager::splitSpace().
getSubspaceCount()
int LayoutManager::Space::getSubspaceCount () const
Get the number of subspaces.
{return subspace_count_; }
incSubSpaceCount()
void LayoutManager::Space::incSubSpaceCount ()
Increment the number of subspaces.
{ subspace_count_ ++; }
Referenced by TreeLayoutManager::splitSpace().
setClient()
void LayoutManager::Space::setClient (Client * client)
Set the client of the space.
Parameters
client
{ Space::client_ = client; }
References client_.
Referenced by TreeLayoutManager::placeClientInSpace(), TreeLayoutManager::removeClientRecursive(), and TreeLayoutManager::splitSpace().
setIndex()
void LayoutManager::Space::setIndex (int index)
Set the index of the space.
Parameters
index
{ Space::index_ = index; }
References index_.
setLeft()
void LayoutManager::Space::setLeft (std::unique_ptr< Space > left)
Set the left child of the space.
Parameters
left
{ this->left_ = std::move(left); }
Referenced by TreeLayoutManager::removeClientRecursive(), and TreeLayoutManager::splitSpace().
setParent()
void LayoutManager::Space::setParent (LayoutManager::Space * parent)
Set the parent of the space.
Parameters
parent
{ Space::parent_ = parent;}
References parent_.
setPos()
void LayoutManager::Space::setPos (const Point & pos)
Set the position of the space.
Parameters
pos
{ Space::pos_ = pos; }
References pos_.
setRight()
void LayoutManager::Space::setRight (std::unique_ptr< Space > right)
Set the right child of the space.
Parameters
right
{ this->right_ = std::move(right); }
Referenced by TreeLayoutManager::removeClientRecursive(), and TreeLayoutManager::splitSpace().
setSize()
void LayoutManager::Space::setSize (const Point & size)
Set the size of the space.
Parameters
size
{ Space::size_ = size; }
References size_.
Referenced by TreeLayoutManager::growSpaceX().
Member Data Documentation
client_
Client* LayoutManager::Space::client_ {} private
{};
Referenced by setClient().
index_
int LayoutManager::Space::index_ private
Referenced by setIndex().
left_
std::unique_ptr<Space> LayoutManager::Space::left_ private
parent_
Space* LayoutManager::Space::parent_ private
Referenced by setParent().
pos_
Point LayoutManager::Space::pos_ private
Referenced by setPos().
right_
std::unique_ptr<Space> LayoutManager::Space::right_ private
size_
Point LayoutManager::Space::size_ private
Referenced by setSize().
subspace_count_
int LayoutManager::Space::subspace_count_ private
The documentation for this class was generated from the following files:
inc/LayoutManager.hpp
src/LayoutManager.cpp