YggdrasilWM: ConfigHandler Class Reference
ConfigHandler Class Reference
ConfigHandler class This class is responsible for handling the configuration file. It is used to read and write the configuration file. And Transmits the configuration to the WindowManager class. The constructor will search for the configuration file in the default paths.
#include <ConfigHandler.hpp>
Public Types
using ConfigValue = std::variant< std::string, int, bool, unsigned long >
Public Member Functions
ConfigHandler ()
Construct a new ConfigHandler object without a path.
ConfigHandler (const std::string configPath)
Construct a new ConfigHandler object with a path, if the path is not valid try to find the file in the default paths.
~ConfigHandler ()
void setConfig (const std::string &key, const std::string &value)
Set a configuration value during runtime.
ConfigValue getConfig (const std::string &key)
Get a configuration value.
void saveConfig ()
bool loadConfig ()
Load the configuration file and parse it into a map.
const std::string & getConfigPath () const
Get the Config Path object.
std::stringstream printConfig ()
Print the configuration to a string stream, this method is only used for debugging purpose and will be removed.
Private Member Functions
std::string findConfigFile () const
Find the configuration file in the default paths.
bool fileExists (const std::string &path) const
Check if a file exists.
std::string expandEnvironmentVariables (const std::string &path) const
Expand environment variables in a string.
std::unordered_map< std::string, ConfigValue > parseJsonToMap (const Json::Value &jsonValue)
Parse a json value to a map.
unsigned long colorCodeToULong (const std::string &colorCode)
Convert a string containing a color code to unsigned long.
Private Attributes
std::string configPath_
std::unordered_map< std::string, ConfigValue > configMap_
Static Private Attributes
static const std::vector< std::string > defaultPaths
Detailed Description
ConfigHandler class This class is responsible for handling the configuration file. It is used to read and write the configuration file. And Transmits the configuration to the WindowManager class. The constructor will search for the configuration file in the default paths.
See also
WindowManager
Member Typedef Documentation
ConfigValue
using ConfigHandler::ConfigValue = std::variant<std::string, int, bool,unsigned long>
Constructor & Destructor Documentation
ConfigHandler() [1/2]
ConfigHandler::ConfigHandler ()
Construct a new ConfigHandler object without a path.
                             : configPath_(""), configMap_() {
    this->configPath_ = findConfigFile();
    if (this->configPath_.empty()) {
        throw std::runtime_error("No config file found.");
    }
    std::cout << "Config file found at: " << this->configPath_ << std::endl;
}
References configPath_, and findConfigFile().
ConfigHandler() [2/2]
ConfigHandler::ConfigHandler (const std::string configPath)
Construct a new ConfigHandler object with a path, if the path is not valid try to find the file in the default paths.
Parameters
configPath
                                                       : configPath_(""), configMap_() {
    if (fileExists(configPath)) {
        this->configPath_ = configPath;
    } else {
        this->configPath_ = findConfigFile();
    }
    if (this->configPath_.empty()) {
        throw std::runtime_error("No config file found.");
    }
    std::cout << "Config file found at: " << this->configPath_ << std::endl;
}
References configPath_, fileExists(), and findConfigFile().
~ConfigHandler()
ConfigHandler::~ConfigHandler () default
Member Function Documentation
colorCodeToULong()
unsigned long ConfigHandler::colorCodeToULong (const std::string & colorCode) private
Convert a string containing a color code to unsigned long.
Parameters
colorCode
Returns
unsigned long color code
{
    if (colorCode.size() != 7 || colorCode[0] != '#' || !isxdigit(colorCode[1])) {
        return 0x000000;
    }
    std::istringstream iss(colorCode.substr(1));
    unsigned long colorValue;
    iss >> std::hex >> colorValue;
    if (iss.fail()) { return 0x000000; }
    return colorValue;
}
Referenced by parseJsonToMap().
expandEnvironmentVariables()
std::string ConfigHandler::expandEnvironmentVariables (const std::string & path) const private
Expand environment variables in a string.
Parameters
path
Returns
expanded string
{
    if (path.empty() || path[0] != '$') {
        return path;
    }
    std::string variable = path.substr(1);
    const char* value = std::getenv(variable.c_str());
    return value ? value : "";
}
Referenced by findConfigFile().
fileExists()
bool ConfigHandler::fileExists (const std::string & path) const private
Check if a file exists.
Parameters
path
Returns
true if the file exists false otherwise
{
    std::ifstream f(path.c_str());
    return f.good();
}
Referenced by ConfigHandler(), and findConfigFile().
findConfigFile()
std::string ConfigHandler::findConfigFile () const private
Find the configuration file in the default paths.
Returns
a string with the path to the configuration file
{
    for (const auto&path : defaultPaths) {
        if (fileExists(expandEnvironmentVariables(path))) {
            return path;
        }
    }
    return "";
}
References defaultPaths, expandEnvironmentVariables(), and fileExists().
Referenced by ConfigHandler(), and ConfigHandler().
getConfig()
ConfigValue ConfigHandler::getConfig (const std::string & key)
Get a configuration value.
Parameters
key
Returns
a variant of string, int, bool or unsigned long
{
    auto it = configMap_.find(key);
    if (it != configMap_.end()) {
        return it->second;
    }
    return ConfigValue {};
}
References configMap_.
Referenced by WindowManager::getTopLevelWindows(), EventHandler::handleFocusIn(), EventHandler::handleFocusOut(), and WindowManager::insertClient().
getConfigPath()
const std::string & ConfigHandler::getConfigPath () const
Get the Config Path object.
Returns
a string with the path to the configuration file
{ return configPath_; }
References configPath_.
Referenced by main().
loadConfig()
bool ConfigHandler::loadConfig ()
Load the configuration file and parse it into a map.
Returns
true if the file was loaded successfully false otherwise
Todo:
: Implement the saveConfig function
{
    std::ifstream file(configPath_);
    if (!file.is_open()) {
        return false;
    }
    try {
        Json::CharReaderBuilder readerBuilder;
        Json::Value root;
        Json::parseFromStream(readerBuilder, file, &root, nullptr);
        configMap_ = parseJsonToMap(root);
        return true;
    } catch (const Json::Exception &e) {
        std::cerr << "Error parsing config file: " << e.what() << std::endl;
        return false;
    }
}
References configMap_, configPath_, and parseJsonToMap().
Referenced by main().
parseJsonToMap()
std::unordered_map< std::string, ConfigValue > ConfigHandler::parseJsonToMap (const Json::Value & jsonValue) private
Parse a json value to a map.
Parameters
jsonValue
Returns
a map with the json values
{
    std::unordered_map<std::string, ConfigValue> result;
    for (const auto& key : jsonValue.getMemberNames()) {
        const Json::Value& jsonSubValue = jsonValue[key];
        if (jsonSubValue.isString()) {
            if (jsonSubValue.asString().size() == 7 && jsonSubValue.asString()[0] == '#') {
                result[key] = colorCodeToULong(jsonSubValue.asString());
            } else {
                result[key] = jsonSubValue.asString();
            }
        } else if (jsonSubValue.isInt()) {
            result[key] = jsonSubValue.asInt();
        } else if (jsonSubValue.isBool()) {
            result[key] = jsonSubValue.asBool();
        } else {
            std::cerr << "Unsupported value type for key: " << key << std::endl;
        }
    }
    return result;
}
References colorCodeToULong().
Referenced by loadConfig().
printConfig()
std::stringstream ConfigHandler::printConfig ()
Print the configuration to a string stream, this method is only used for debugging purpose and will be removed.
Returns
{
    std::stringstream result;
    result << "\n\tConfig file: " << configPath_ << std::endl;
    for (const auto& keyValue : configMap_) {
        const auto& key = keyValue.first;
        const ConfigValue& value = keyValue.second;
        std::visit([&result, &key](const auto& v) {
            result << "\t\t" << key << " : " << v << std::endl;
        }, value);
    }
    return result;
}
References configMap_, and configPath_.
Referenced by main().
saveConfig()
void ConfigHandler::saveConfig ()
{
}
setConfig()
void ConfigHandler::setConfig (const std::string & key, const std::string & value)
Set a configuration value during runtime.
Parameters
key
value
{
}
Member Data Documentation
configMap_
std::unordered_map<std::string,ConfigValue> ConfigHandler::configMap_ private
Referenced by getConfig(), loadConfig(), and printConfig().
configPath_
std::string ConfigHandler::configPath_ private
Referenced by ConfigHandler(), ConfigHandler(), getConfigPath(), loadConfig(), and printConfig().
defaultPaths
const std::vector< std::string > ConfigHandler::defaultPaths static private
Initial value:
= {
        "config.json",
        "$HOME/.config/YggdrasilWM/config.json",
        "$HOME/.YggdrasilWM/config.json",
        "/etc/YggdrasilWM/config.json"
}
                    {
public:
    using ConfigValue = std::variant<std::string, int, bool,unsigned long>;
    ConfigHandler();
    ConfigHandler(const std::string configPath);
    ~ConfigHandler();
    void setConfig(const std::string &key, const std::string &value);
    ConfigValue getConfig(const std::string &key);
    void saveConfig();
    bool loadConfig();
    const std::string &getConfigPath() const;
    std::stringstream printConfig();
private:
    static const std::vector<std::string> defaultPaths;
    std::string configPath_;
    std::unordered_map<std::string,ConfigValue> configMap_;
    std::string findConfigFile() const;
    bool fileExists(const std::string &path) const;
    std::string expandEnvironmentVariables(const std::string &path) const;
    std::unordered_map<std::string, ConfigValue> parseJsonToMap(const Json::Value& jsonValue);
    unsigned long colorCodeToULong(const std::string &colorCode);
};
#endif //YGGDRASILWM_CONFIGHANDLER_HPP
Referenced by findConfigFile().
The documentation for this class was generated from the following files:
inc/ConfigHandler.hpp
src/ConfigHandler.cpp