YggdrasilWM: Logger Class Reference
Logger Class Reference
Logger class This class is responsible for logging. It can be created with a file name or an ostream. The log level can be set to filter the messages.
#include <Logger.hpp>
Public Member Functions
Logger (const Logger &)=delete
Logger & operator= (const Logger &)=delete
virtual ~Logger ()
Destroy the Logger:: Logger object closes the log file if it was opened. The destructor is virtual to allow for subclassing.for gmock.
virtual void Log (const std::string &message, LogLevel level) const
Log a message This method logs a message to the log file or stream. The message is only logged if the log level is high enough. the time and log level are prepended to the message. The method is virtual to allow for subclassing.for gmock.
Static Public Member Functions
static void Create (const std::string &logFile, LogLevel logLevel)
static void Create (std::ostream &output, LogLevel logLevel)
static Logger * GetInstance ()
Get the Logger object.
static void Destroy ()
Destroy the Logger:: Logger object closes the log file if it was opened.
Private Member Functions
Logger (const std::string &logFile, LogLevel logLevel)
Construct a new Logger:: Logger object This constructor is used when the user wants to log to a file.
Logger (std::ostream &output, LogLevel logLevel)
Construct a new Logger:: Logger object This constructor is used when the user wants to log to a stream.
Static Private Member Functions
static std::string GetLogLevel (LogLevel level)
Get the log level as a string.
static std::string GetTime ()
Get the current time.
Private Attributes
bool streamIsFile_
std::ostream * logStream_
LogLevel logLevel_
Static Private Attributes
static Logger * instance_ = nullptr
Detailed Description
Logger class This class is responsible for logging. It can be created with a file name or an ostream. The log level can be set to filter the messages.
Constructor & Destructor Documentation
Logger() [1/3]
Logger::Logger (const Logger &) delete
Referenced by Create().
~Logger()
Logger::~Logger () virtual
Destroy the Logger:: Logger object closes the log file if it was opened. The destructor is virtual to allow for subclassing.for gmock.
                 {
     *logStream_ << GetTime() << "Closing Session \n"
                 << " =================================================================================== "
                 << std::endl;
     if (streamIsFile_) {
         if (dynamic_cast<std::ofstream*>(logStream_) != nullptr) {
             dynamic_cast<std::ofstream*>(logStream_)->close();
         }
         delete logStream_;
     }
 }
References GetTime(), logStream_, and streamIsFile_.
Logger() [2/3]
Logger::Logger (const std::string & logFile, LogLevel logLevel) private
Construct a new Logger:: Logger object This constructor is used when the user wants to log to a file.
Parameters
logFile the file to log to
logLevel level of logging 0: info, 1: warning, 2: error
         : logLevel_(logLevel) {
     auto* fileStream = new std::ofstream(logFile, std::ios::out | std::ios::app);
     if (!fileStream->good()) {
         std::cerr << "Failed to open log file: " << logFile << std::endl;
         delete fileStream;
         throw std::runtime_error("Failed to open log file.");
     }
     logStream_ = fileStream;
     streamIsFile_ = true;
 }
References logStream_, and streamIsFile_.
Logger() [3/3]
Logger::Logger (std::ostream & output, LogLevel logLevel) private
Construct a new Logger:: Logger object This constructor is used when the user wants to log to a stream.
Parameters
output the stream to log to
logLevel level of logging 0: info, 1: warning, 2: error
         : logStream_(&output), logLevel_(logLevel) {
     streamIsFile_ = false;
 }
References streamIsFile_.
Member Function Documentation
Create() [1/2]
void Logger::Create (const std::string & logFile, LogLevel logLevel) static
{
     if (instance_ == nullptr) {
         instance_ = new Logger(logFile, logLevel);
     }
 }
References instance_, and Logger().
Referenced by main().
Create() [2/2]
void Logger::Create (std::ostream & output, LogLevel logLevel) static
{
     if (instance_ == nullptr) {
         instance_ = new Logger(output, logLevel);
     }
 }
References instance_, and Logger().
Destroy()
static void Logger::Destroy () static
Destroy the Logger:: Logger object closes the log file if it was opened.
                      {
     if (instance_ != nullptr) {
         delete instance_;
         instance_ = nullptr;
     }
 }
References instance_.
Referenced by main().
GetInstance()
static Logger * Logger::GetInstance () static
Get the Logger object.
Returns
{
     if (instance_ == nullptr) {
         throw std::runtime_error("Logger instance not created");
     }
     return instance_;
 }
References instance_.
Referenced by WindowManager::addGroupsFromConfig(), Bar::addWidget(), Client::Client(), ConfigFileHandler::ConfigFileHandler(), ConfigHandler::configInit(), ConfigDataBar::configInit(), ConfigDataGroup::configInit(), ConfigDataGroups::configInit(), ConfigDataWidget::configInit(), ConfigDataBars::configInit(), ConfigDataBindings::configInit(), WindowManager::create(), EventHandler::dispatchEvent(), FocusGroup::execute(), Spawn::execute(), Client::frame(), WindowManager::getTopLevelWindows(), Bars::getWidgetTypeHandle(), Group::Group(), EventHandler::handleButtonPress(), EventHandler::handleDestroyNotify(), EventHandler::handleFocusIn(), EventHandler::handleFocusOut(), ConfigDataBindings::handleKeypressEvent(), EventHandler::handleMapNotify(), EventHandler::handleMapRequest(), ewmh::handleMessage(), EventHandler::handlePropertyNotify(), EventHandler::handleUnmapNotify(), Bars::init(), Binding::init_keycode(), ewmh::initEwmh(), WindowManager::insertClient(), main(), Client::move(), Group::moveClientToGroup(), WindowManager::OnXError(), ConfigFileHandler::readConfig(), Group::removeClient(), Client::resize(), Client::restack(), Bars::run(), WindowManager::Run(), Group::switchFrom(), Group::switchTo(), Client::unframe(), ewmh::updateDesktopGeometry(), ConfigFileHandler::writeConfig(), Bars::~Bars(), Client::~Client(), and WindowManager::~WindowManager().
GetLogLevel()
std::string Logger::GetLogLevel (LogLevel level) static private
Get the log level as a string.
Parameters
level
Returns
a string representation of the log level
{
     switch (level) {
         case L_INFO:
             return "[INFO]\t";
         case L_WARNING:
             return "[WARNING]\t";
         case L_ERROR:
             return "[ERROR]\t";
         default:
             return "[UNKNOWN]\t";
     }
 }
References L_ERROR, L_INFO, and L_WARNING.
Referenced by Log().
GetTime()
std::string Logger::GetTime () static private
Get the current time.
This method returns the current time in the format: [YYYY-MM-DD-HH:MM:SS]
Returns
{
     time_t now = time(nullptr);
     tm* ltm = localtime(&now);
     std::stringstream ss;
     ss << std::put_time(ltm, "[%Y-%m-%d-%H:%M:%S]\t");
     return ss.str();
 }
Referenced by Log(), and ~Logger().
Log()
void Logger::Log (const std::string & message, LogLevel level) const virtual
Log a message This method logs a message to the log file or stream. The message is only logged if the log level is high enough. the time and log level are prepended to the message. The method is virtual to allow for subclassing.for gmock.
Parameters
message the message to log
level the level of the message
{
     if (level < logLevel_) {
         return;
     }
     *logStream_ << GetTime() << GetLogLevel(level) << message << std::endl;
 }
References GetLogLevel(), GetTime(), logLevel_, and logStream_.
Referenced by WindowManager::addGroupsFromConfig(), Bar::addWidget(), Client::Client(), ConfigFileHandler::ConfigFileHandler(), ConfigHandler::configInit(), ConfigDataBar::configInit(), ConfigDataGroup::configInit(), ConfigDataGroups::configInit(), ConfigDataWidget::configInit(), ConfigDataBars::configInit(), ConfigDataBindings::configInit(), WindowManager::create(), EventHandler::dispatchEvent(), FocusGroup::execute(), Spawn::execute(), Client::frame(), WindowManager::getTopLevelWindows(), Bars::getWidgetTypeHandle(), Group::Group(), EventHandler::handleButtonPress(), EventHandler::handleDestroyNotify(), EventHandler::handleFocusIn(), EventHandler::handleFocusOut(), ConfigDataBindings::handleKeypressEvent(), EventHandler::handleMapNotify(), EventHandler::handleMapRequest(), ewmh::handleMessage(), EventHandler::handlePropertyNotify(), EventHandler::handleUnmapNotify(), Bars::init(), Binding::init_keycode(), ewmh::initEwmh(), WindowManager::insertClient(), main(), Client::move(), Group::moveClientToGroup(), WindowManager::OnXError(), ConfigFileHandler::readConfig(), Group::removeClient(), Client::resize(), Client::restack(), Bars::run(), WindowManager::Run(), Group::switchFrom(), Group::switchTo(), Client::unframe(), ewmh::updateDesktopGeometry(), ConfigFileHandler::writeConfig(), Bars::~Bars(), Client::~Client(), and WindowManager::~WindowManager().
operator=()
Logger& Logger::operator= (const Logger &) delete
Member Data Documentation
instance_
Logger * Logger::instance_ = nullptr static private
Referenced by Create(), Destroy(), and GetInstance().
logLevel_
LogLevel Logger::logLevel_ private
Referenced by Log().
logStream_
std::ostream* Logger::logStream_ private
Referenced by Log(), Logger(), and ~Logger().
streamIsFile_
bool Logger::streamIsFile_ private
Referenced by Logger(), and ~Logger().
The documentation for this class was generated from the following files:
inc/Logger.hpp
src/Logger.cpp