YggdrasilWM: ConfigFileHandler Class Reference
ConfigFileHandler Class Reference
Handle file I/O and JSON parsing for the configuration file. If no path is provided, it will search for the configuration file in the default paths.
#include <ConfigFileHandler.hpp>
Public Member Functions
ConfigFileHandler ()
Construct a new ConfigFileHandler object without a path.
ConfigFileHandler (const std::string &configPath)
~ConfigFileHandler ()
void readConfig ()
Read the configuration file Store the JSon root object in Json::Value root_ Throws exceptions in case of file i/o error Catch Parsing Errors and log them with Logger Object.
void writeConfig (const Json::Value &root)
Write the configuration file Store the JSon root object in the configPath file Throws exceptions in case of file i/o error.
const Json::Value & getRoot ()
Get the root JSON object.
std::string getConfigPath ()
Static Private Member Functions
static std::string findConfigFile ()
Find the configuration file in the default paths.
static bool fileExists (const std::string &path)
Check if a file exists by trying to open it.
static std::string expandEnvironmentVariables (const std::string &path)
Expand environment variables in a path.
Private Attributes
std::string configPath_
Json::Value root_
Static Private Attributes
static const std::vector< std::string > defaultPaths
Detailed Description
Handle file I/O and JSON parsing for the configuration file. If no path is provided, it will search for the configuration file in the default paths.
Constructor & Destructor Documentation
ConfigFileHandler() [1/2]
ConfigFileHandler::ConfigFileHandler ()
Construct a new ConfigFileHandler object without a path.
                                      : configPath_(""),root_() {
     this->configPath_ = findConfigFile();
     if (this->configPath_.empty()) {
         throw std::runtime_error("No config file found.");
     }
     Logger::GetInstance()->Log("Config file found at: " + this->configPath_ ,L_INFO);
 }
References configPath_, findConfigFile(), Logger::GetInstance(), L_INFO, and Logger::Log().
ConfigFileHandler() [2/2]
ConfigFileHandler::ConfigFileHandler (const std::string & configPath) explicit
                                                                 : configPath_("") {
     if (fileExists(configPath)) {
         this->configPath_ = configPath;
     } else {
         this->configPath_ = findConfigFile();
     }
     if (this->configPath_.empty()) {
         throw std::runtime_error("No config file found.");
     }
     Logger::GetInstance()->Log("Using Config file : " + this->configPath_,L_INFO );
 }
References configPath_, fileExists(), findConfigFile(), Logger::GetInstance(), L_INFO, and Logger::Log().
~ConfigFileHandler()
ConfigFileHandler::~ConfigFileHandler ()
 {}
Member Function Documentation
expandEnvironmentVariables()
std::string ConfigFileHandler::expandEnvironmentVariables (const std::string & path) static private
Expand environment variables in a path.
Parameters
path
Returns
Expanded path as a std::string
{
     if (path.empty() || path[0] != '$') {
         return path;
     }
     std::string variable = path.substr(1);
     const char* value = std::getenv(variable.c_str());
     return value ? value : "";
 }
Referenced by findConfigFile().
fileExists()
bool ConfigFileHandler::fileExists (const std::string & path) static private
Check if a file exists by trying to open it.
Parameters
path
Returns
{
     std::ifstream f(path.c_str());
     return f.good();
 }
Referenced by ConfigFileHandler(), and findConfigFile().
findConfigFile()
std::string ConfigFileHandler::findConfigFile () static private
Find the configuration file in the default paths.
Returns
The full path to the configuration file
{
     for (const auto&path : defaultPaths) {
         if (fileExists(expandEnvironmentVariables(path))) {
             return path;
         }
     }
     return "";
 }
References defaultPaths, expandEnvironmentVariables(), and fileExists().
Referenced by ConfigFileHandler().
getConfigPath()
std::string ConfigFileHandler::getConfigPath ()
{
     return configPath_;
 }
References configPath_.
getRoot()
Json::Value ConfigFileHandler::getRoot ()
Get the root JSON object.
Returns
Json::Value The root JSON object
 { return root_; }
References root_.
readConfig()
void ConfigFileHandler::readConfig ()
Read the configuration file Store the JSon root object in Json::Value root_ Throws exceptions in case of file i/o error Catch Parsing Errors and log them with Logger Object.
{
     std::ifstream file(configPath_);
     if (!file.is_open())
         throw std::runtime_error("Failed to open config file");
     try {
         Json::CharReaderBuilder readerBuilder;
         Json::parseFromStream(readerBuilder, file, &root_, nullptr);
         file.close();
     } catch (Json::Exception &e) {
         Logger::GetInstance()->Log("Failed to parse config file: " + std::string(e.what()),L_ERROR);
     }
 }
References configPath_, Logger::GetInstance(), L_ERROR, Logger::Log(), and root_.
writeConfig()
void ConfigFileHandler::writeConfig (const Json::Value & config)
Write the configuration file Store the JSon root object in the configPath file Throws exceptions in case of file i/o error.
Parameters
config The root JSON object to write
{
     std::ofstream file(configPath_);
     if (!file.is_open())
         throw std::runtime_error("Failed to open config file");
     try {
         Json::StreamWriterBuilder writer;
         writer["indentation"] = "\t";
         std::string output = Json::writeString(writer, root);
         file << output;
         file.close();
     } catch (Json::Exception &e) {
         Logger::GetInstance()->Log("Failed to write config file: " + std::string(e.what()),L_ERROR);
     }
 }
References configPath_, Logger::GetInstance(), L_ERROR, and Logger::Log().
Member Data Documentation
configPath_
std::string ConfigFileHandler::configPath_ private
Referenced by ConfigFileHandler(), getConfigPath(), readConfig(), and writeConfig().
defaultPaths
const std::vector< std::string > ConfigFileHandler::defaultPaths static private
Initial value:
= {
        "config.json",
        "$HOME/.config/YggdrasilWM/config.json",
        "$HOME/.YggdrasilWM/config.json",
        "/etc/YggdrasilWM/config.json"
}
Referenced by findConfigFile().
root_
Json::Value ConfigFileHandler::root_ private
Referenced by getRoot(), and readConfig().
The documentation for this class was generated from the following files:
inc/Config/ConfigFileHandler.hpp
src/Config/ConfigFileHandler.cpp