YggdrasilWM: Group Class Reference
Group Class Reference
Groups are defined in the config file. Each group use a specific layout manager and manage it's list of clients, a client can be in multiple groups.
#include <Group.hpp>
Public Member Functions
Group (const std::shared_ptr< ConfigDataGroup > &config, std::shared_ptr< BaseX11Wrapper > x11Wrapper, Display *display, Window root)
Group constructor.
~Group ()
Group destructor.
void addClient (Window window, std::shared_ptr< Client > client)
Add a client to the group.
void removeClient (Window window)
Definitely remove a client from the group.
void removeClient (Client *client)
Definitely remove a client from the group.
void moveClientToGroup (Window window, Group *group)
Move a client to another group.
void setActive (bool active)
Set the group as active.
bool isActive () const
Check if the group is active.
void setName (std::string name)
Set the name of the group.
std::string getName ()
Get the name of the group.
std::shared_ptr< Client > getClient (Window window)
Get a client from the group.
std::unordered_map< Window, std::shared_ptr< Client > > getClients ()
Get the list of clients of the group.
std::shared_ptr< LayoutManager > getLayoutManager ()
Get the layout manager of the group.
void switchTo ()
Switch to this group Set this group as active, switch the layout manager and map the clients.
void switchFrom ()
Switch from this group Set this group as inactive, switch the layout manager and unmap the clients.
int getBorderSize () const
Get the border size of the group.
int getGap () const
Get the gap of the group.
unsigned long getInactiveColor () const
Get the inactive color of the group.
unsigned long getActiveColor () const
Get the active color of the group.
void resize (unsigned int sizeX, unsigned int sizeY, unsigned int posX, unsigned int posY)
Private Attributes
std::string name_
std::unordered_map< Window, std::shared_ptr< Client > > clients_
std::shared_ptr< LayoutManager > layoutManager_
int borderSize_
int gap_
unsigned long inactiveColor_
unsigned long activeColor_
int barHeight_
bool active_ {}
std::shared_ptr< BaseX11Wrapper > wrapper
Detailed Description
Groups are defined in the config file. Each group use a specific layout manager and manage it's list of clients, a client can be in multiple groups.
Todo:
Rules on the WM_CLASS of the client can be defined in the config file.
Constructor & Destructor Documentation
Group()
Group::Group (const std::shared_ptr< ConfigDataGroup > & config, std::shared_ptr< BaseX11Wrapper > x11Wrapper, Display * display, Window root) explicit
Group constructor.
Parameters
name The name of the group
borderSize The size of the border
gap The gap between the clients
barHeight The height of the bar
layoutType The layout type
Todo:
add the other layout types
{
     name_ = config->getGroupName();
     LayoutType layoutType;
     if (config->getGroupLayout() == "Tree") {
         layoutType = TREE;
     } else if (config->getGroupLayout() == "Max") {
         layoutType = MAX;
     } else if (config->getGroupLayout() == "MasterVertical") {
         layoutType = MASTER_VERTICAL;
     } else if (config->getGroupLayout() == "MasterHorizontal") {
         layoutType = MASTER_HORIZONTAL;
     } else {
         layoutType = TREE;
     }
     wrapper = x11Wrapper;
     borderSize_ = config->getGroupBorderWidth();
     gap_ = config->getGroupGap();
     inactiveColor_ = config->getGroupInactiveColor();
     activeColor_ = config->getGroupActiveColor();
     barHeight_ = 30;
     active_ = false;
     Logger::GetInstance()->Log("Group Created [" + name_ + "]", L_INFO);
     int size_x = wrapper->displayWidth(display, wrapper->defaultScreen(display));
     int size_y = wrapper->displayHeight(display, wrapper->defaultScreen(display));
     switch (layoutType) {
         case TREE:
             layoutManager_ = std::make_shared<TreeLayoutManager>(display,
                                                    root,
                                                    size_x,
                                                    size_y,
                                                    0,
                                                    0,
                                                    borderSize_,
                                                    gap_,
                                                    barHeight_);
             break;
         case MAX:
             break;
         case MASTER_VERTICAL:
             layoutManager_ = std::make_shared<TreeLayoutManager>(display,
                                                    root,
                                                    size_x,
                                                    size_y,
                                                    0,
                                                    0,
                                                    borderSize_,
                                                    gap_,
                                                    barHeight_);
             break;
         case MASTER_HORIZONTAL:
             layoutManager_ = std::make_shared<TreeLayoutManager>(display,
                                                    root,
                                                    size_x,
                                                    size_y,
                                                    0,
                                                    0,
                                                    borderSize_,
                                                    gap_,
                                                    barHeight_);
             break;
         default:
             layoutManager_ = std::make_shared<TreeLayoutManager>(display,
                                                    root,
                                                    size_x,
                                                    size_y,
                                                    0,
                                                    0,
                                                    borderSize_,
                                                    gap_,
                                                    barHeight_);
             break;
     }
 }
References active_, activeColor_, barHeight_, borderSize_, gap_, Logger::GetInstance(), inactiveColor_, L_INFO, layoutManager_, Logger::Log(), MASTER_HORIZONTAL, MASTER_VERTICAL, MAX, name_, TREE, and wrapper.
~Group()
Group::~Group ()
Group destructor.
 { }
Member Function Documentation
addClient()
void Group::addClient (Window window, std::shared_ptr< Client > client)
Add a client to the group.
Parameters
window
client
{
     clients_[window] = client;
     layoutManager_->addClient(client);
 }
References clients_, and layoutManager_.
Referenced by moveClientToGroup().
getActiveColor()
unsigned long Group::getActiveColor () const
Get the active color of the group.
Returns
 { return activeColor_; }
References activeColor_.
getBorderSize()
int Group::getBorderSize () const
Get the border size of the group.
Returns
 { return borderSize_; }
References borderSize_.
getClient()
Client * Group::getClient (Window window)
Get a client from the group.
Parameters
window
 { return clients_[window]; }
References clients_.
getClients()
std::unordered_map< Window, Client * > Group::getClients ()
Get the list of clients of the group.
 { return clients_; }
References clients_.
Referenced by switchFrom(), and switchTo().
getGap()
int Group::getGap () const
Get the gap of the group.
Returns
 { return gap_; }
References gap_.
getInactiveColor()
unsigned long Group::getInactiveColor () const
Get the inactive color of the group.
Returns
 { return inactiveColor_; }
References inactiveColor_.
getLayoutManager()
LayoutManager * Group::getLayoutManager ()
Get the layout manager of the group.
 { return layoutManager_; }
References layoutManager_.
getName()
std::string Group::getName ()
Get the name of the group.
Returns
 { return name_; }
References name_.
isActive()
bool Group::isActive () const
Check if the group is active.
Returns
bool
 { return active_; }
References active_.
moveClientToGroup()
void Group::moveClientToGroup (Window window, Group * group)
Move a client to another group.
Parameters
window
group
{
     clients_.erase(window);
     try {
         auto c = WindowManager::getInstance()->getClient(window);
         group->addClient(window, c);
     } catch (const std::exception &e) {
         Logger::GetInstance()->Log(e.what(), L_ERROR);
     }
 }
References addClient(), clients_, WindowManager::getClient(), Logger::GetInstance(), WindowManager::getInstance(), L_ERROR, and Logger::Log().
removeClient() [1/2]
void Group::removeClient (Client * client)
Definitely remove a client from the group.
Parameters
client
{
     clients_.erase(client->getWindow());
     layoutManager_->removeClient(client);
 }
References clients_, Client::getWindow(), and layoutManager_.
removeClient() [2/2]
void Group::removeClient (Window window)
Definitely remove a client from the group.
Parameters
window
{
     clients_.erase(window);
     try {
         auto c = WindowManager::getInstance()->getClient(window);
         layoutManager_->removeClient(c.get());
     } catch (const std::exception &e) {
         Logger::GetInstance()->Log(e.what(), L_ERROR);
     }
 }
References clients_, WindowManager::getClient(), Logger::GetInstance(), WindowManager::getInstance(), L_ERROR, layoutManager_, and Logger::Log().
resize()
void Group::resize (unsigned int sizeX, unsigned int sizeY, unsigned int posX, unsigned int posY)
{
     layoutManager_->updateGeometry(sizeX, sizeY, posX, posY);
 }
References layoutManager_.
setActive()
void Group::setActive (bool active)
Set the group as active.
Parameters
active
 { active_ = active; }
References active_.
setName()
void Group::setName (std::string name)
Set the name of the group.
Parameters
name
{
     name_ = std::move(name);
 }
References name_.
switchFrom()
void Group::switchFrom ()
Switch from this group Set this group as inactive, switch the layout manager and unmap the clients.
{
     Logger::GetInstance()->Log("Group switched from [" + name_ + "]", L_INFO);
     for (auto &client: WindowManager::getInstance()->getClients()) {
         if (client.second->getGroup().get() == this) {
 //          client.second->unframe();
             wrapper->unmapWindow(WindowManager::getInstance()->getDisplay(), client.second->getFrame());
         }
     }
     this->active_ = false;
 }
References active_, getClients(), Logger::GetInstance(), WindowManager::getInstance(), L_INFO, Logger::Log(), name_, and wrapper.
switchTo()
void Group::switchTo ()
Switch to this group Set this group as active, switch the layout manager and map the clients.
                      {
     Logger::GetInstance()->Log("Group switched to [" + name_ + "]", L_INFO);
     for (auto &client: WindowManager::getInstance()->getClients()) {
         if (client.second->getGroup().get() == this) {
             wrapper->mapWindow(WindowManager::getInstance()->getDisplay(), client.second->getFrame());
         }
     }
     this->active_= true;
     WindowManager::getInstance()->setActiveGroup(shared_from_this());
 }
References active_, getClients(), Logger::GetInstance(), WindowManager::getInstance(), L_INFO, Logger::Log(), name_, WindowManager::setActiveGroup(), and wrapper.
Member Data Documentation
active_
bool Group::active_ {} private
Referenced by Group(), isActive(), setActive(), switchFrom(), and switchTo().
activeColor_
unsigned long Group::activeColor_ private
Referenced by getActiveColor(), and Group().
barHeight_
int Group::barHeight_ private
Referenced by Group().
borderSize_
int Group::borderSize_ private
Referenced by getBorderSize(), and Group().
clients_
std::unordered_map<Window, std::shared_ptr<Client> > Group::clients_ private
Referenced by addClient(), getClient(), getClients(), moveClientToGroup(), and removeClient().
gap_
int Group::gap_ private
Referenced by getGap(), and Group().
inactiveColor_
unsigned long Group::inactiveColor_ private
Referenced by getInactiveColor(), and Group().
layoutManager_
std::shared_ptr<LayoutManager> Group::layoutManager_ private
Referenced by addClient(), getLayoutManager(), Group(), removeClient(), and resize().
name_
std::string Group::name_ private
Referenced by getName(), Group(), setName(), switchFrom(), and switchTo().
wrapper
std::shared_ptr<BaseX11Wrapper> Group::wrapper private
Referenced by Group(), switchFrom(), and switchTo().
The documentation for this class was generated from the following files:
inc/Group.hpp
src/Group.cpp