YggdrasilWM: inc/WindowManager.hpp File Reference
WindowManager.hpp File Reference
WindowManager class header.
#include <X11/Xlib.h>
#include <memory>
#include <string>
#include <unordered_map>
#include <chrono>
#include "Logger.hpp"
#include "Client.hpp"
#include "Layouts/TreeLayoutManager.hpp"
#include "Config/ConfigHandler.hpp"
#include <iostream>
#include <algorithm>
#include <csignal>
#include <mutex>
Classes
class WindowManager
WindowManager class This class is responsible for managing the windows.in an X11 session. It is the main class of the project. It should be instantiated only via the static create function. You must use the init function to initialize the WindowManager. The Run function is the main loop of the WindowManager.
Functions
void handleSIGHUP (int signal)
Detailed Description
WindowManager class header.
Yb dP 8 w 8 Yb dP 8b d8 YbdP .d88 .d88 .d88 8d8b .d88 d88b w 8 Yb db dP 8YbmdP8 YP 8 8 8 8 8 8 8P 8 8 Yb. 8 8 YbdPYbdP 8 " 8 88Y88 Y88Y88 8 `Y88 Y88P 8 8 YP YP 8 8 wwdP wwdP Yggdrasil Window Manager https://github.com/corecaps/YggdrasilWM Copyright (C) 2024 jgarcia jgarc.nosp@m.ia@s.nosp@m.tuden.nosp@m.t.42.nosp@m..fr corec.nosp@m.aps@.nosp@m.gmail.nosp@m..com
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.
Date
2024-02-11
Function Documentation
handleSIGHUP()
void handleSIGHUP (int signal)
{
     std::cout << "Caught signal " << signal << std::endl;
     if (WindowManager::getInstance() != nullptr) {
         WindowManager::getInstance()->Stop();
     }
 }
References WindowManager::getInstance(), and WindowManager::Stop().
Referenced by WindowManager::init().