YggdrasilWM: ConfigDataBindings Class Reference
ConfigDataBindings Class Reference
ConfigDataBindings class. This class is used to handle the bindings configuration it instanciates the bindings in a vector it handle grabbing keys and handle keypress events.
#include <ConfigDataBindings.hpp>
Public Member Functions
ConfigDataBindings ()
~ConfigDataBindings () override
void configInit (const Json::Value &root_) override
Parse the Json::Value object to initialize the bindings Instanciate the bindings in a vector.
void initKeycodes (Display *display, BaseX11Wrapper *x11Wrapper)
Initialize the keycodes This method is called by the WindowManager to initialize the keycodes after the display and the x11Wrapper are initialized.
Json::Value configSave () override
Build a Json::Value object with the configuration.
void grabKeys (Display *display, Window window)
Grab the keys from the bindings GrabKeys is called on the root window on initialisation of the WindowManager and then on each new window creation that is managed by the WindowManager.
void handleKeypressEvent (const XKeyEvent *event)
Handle the keypress event This method is called by the EventManager to avoid handling bindings and their interface in the EventHandle class.
const std::vector< Binding * > & getBindings () const
Private Attributes
std::vector< Binding * > bindings_
Detailed Description
ConfigDataBindings class. This class is used to handle the bindings configuration it instanciates the bindings in a vector it handle grabbing keys and handle keypress events.
Constructor & Destructor Documentation
ConfigDataBindings()
ConfigDataBindings::ConfigDataBindings ()
 : bindings_(){}
~ConfigDataBindings()
ConfigDataBindings::~ConfigDataBindings () override
{
     for (auto &binding : bindings_) {
         delete binding;
     }
 }
References bindings_.
Member Function Documentation
configInit()
void ConfigDataBindings::configInit (const Json::Value & root_) override virtual
Parse the Json::Value object to initialize the bindings Instanciate the bindings in a vector.
Parameters
root_ the Json::Value object containing the bindings
Implements ConfigDataBase.
{
     std::vector<std::string> modKeys = root.getMemberNames();
     for (auto &modKey : modKeys) {
         Json::Value bindings = root[modKey];
         for (auto &binding : bindings) {
             std::string key = binding["Key"].asString();
             std::string command = binding["Action"].asString();
             std::string arg = binding["Argument"].asString();
             auto b = new Binding();
             b->init(modKey, key, command, arg);
             bindings_.push_back(b);
         }
     }
     Logger::GetInstance()->Log("Successfully added " + std::to_string(bindings_.size()) + " bindings", L_INFO);
 }
References bindings_, Logger::GetInstance(), L_INFO, and Logger::Log().
configSave()
Json::Value ConfigDataBindings::configSave () override virtual
Build a Json::Value object with the configuration.
Returns
Json::Value Object with the current runtime configuration
Implements ConfigDataBase.
{
     return Json::Value();
 }
getBindings()
const std::vector< Binding * > & ConfigDataBindings::getBindings () const
{
     return bindings_;
 }
References bindings_.
grabKeys()
void ConfigDataBindings::grabKeys (Display * display, Window window)
Grab the keys from the bindings GrabKeys is called on the root window on initialisation of the WindowManager and then on each new window creation that is managed by the WindowManager.
Parameters
display
window
{
     for (auto &binding : bindings_) {
         XGrabKey(display, binding->getKeyCode(), binding->getModMask(), window, true, GrabModeAsync, GrabModeAsync);
     }
     XFlush(display);
 }
References bindings_.
handleKeypressEvent()
void ConfigDataBindings::handleKeypressEvent (const XKeyEvent * event)
Handle the keypress event This method is called by the EventManager to avoid handling bindings and their interface in the EventHandle class.
Parameters
event must be converted to const XKeyEvent *event
{
     unsigned int keyCode = event->keycode;
     bool modOk = false;
     for (auto &binding : bindings_) {
         modOk = event->state & binding->getModMask();
         if (binding->getKeyCode() == keyCode && modOk) {
             if (binding->getCommandName() == "Grow") {
                 binding->execute(event);
             } else {
                 binding->execute(nullptr);
             }
             Logger::GetInstance()->Log("[" +
                                         binding->getMod()
                                         + "+"
                                         + binding->getKey()
                                         +"] ->\t"
                                         + binding->getCommandName()
                                         + " ["
                                         + binding->getArgs()
                                         + "]",L_INFO);
         }
     }
 }
References bindings_, Logger::GetInstance(), L_INFO, and Logger::Log().
initKeycodes()
void ConfigDataBindings::initKeycodes (Display * display, BaseX11Wrapper * x11Wrapper)
Initialize the keycodes This method is called by the WindowManager to initialize the keycodes after the display and the x11Wrapper are initialized.
Parameters
display
x11Wrapper
{
     for (auto &binding : bindings_) {
         binding->init_keycode(display,x11Wrapper);
     }
 }
References bindings_.
Member Data Documentation
bindings_
std::vector<Binding *> ConfigDataBindings::bindings_ private
Referenced by configInit(), getBindings(), grabKeys(), handleKeypressEvent(), initKeycodes(), and ~ConfigDataBindings().
The documentation for this class was generated from the following files:
inc/Config/ConfigDataBindings.hpp
src/Config/ConfigDataBindings.cpp