YggdrasilWM: FocusGroup Class Reference
FocusGroup Class Reference
FocusGroup implement the mecanism to switch between group.
#include <FocusGroup.hpp>
Public Member Functions
FocusGroup ()
~FocusGroup () override=default
void execute (const std::string &args) override
switch from the current active group to the group index passed as argument
Detailed Description
FocusGroup implement the mecanism to switch between group.
Constructor & Destructor Documentation
FocusGroup()
FocusGroup::FocusGroup ()
{
 }
~FocusGroup()
FocusGroup::~FocusGroup () override default
Member Function Documentation
execute()
void FocusGroup::execute (const std::string & args) override virtual
switch from the current active group to the group index passed as argument
Parameters
args the string will be parsed to an integer to switch to the group index
Implements CommandBase.
{
     int index;
     try {
         index = std::stoi(args) - 1;
     } catch ( const std::exception &e) {
         Logger::GetInstance()->Log("Focus Group argument is not convertible to int",L_ERROR);
     }
     WindowManager *wm = WindowManager::getInstance();
     if (index < 0)
         index = 0;
     if (index > wm->getGroups().size())
         index = wm->getGroups().size();
     if (wm->getActiveGroup() != wm->getGroups()[index]) {
         wm->getActiveGroup()->switchFrom();
         wm->getGroups()[index]->switchTo();
     }
 }
References WindowManager::getActiveGroup(), WindowManager::getGroups(), Logger::GetInstance(), WindowManager::getInstance(), L_ERROR, and Logger::Log().
The documentation for this class was generated from the following files:
inc/Commands/FocusGroup.hpp
src/Commands/FocusGroup.cpp