YggdrasilWM: src/WindowManager.cpp File Reference
WindowManager.cpp File Reference
#include <X11/Xlib.h>
#include "WindowManager.hpp"
#include "EventHandler.hpp"
#include "Config/ConfigDataBars.hpp"
#include "Config/ConfigHandler.hpp"
#include "Config/ConfigDataGroups.hpp"
#include "Config/ConfigDataBindings.hpp"
#include "Bars/Bars.hpp"
#include "Bars/TSBarsData.hpp"
#include "Group.hpp"
#include "Ewmh.hpp"
#include "X11wrapper/baseX11Wrapper.hpp"
#include "YggdrasilExceptions.hpp"
Functions
void handleSIGHUP (int signal)
Function Documentation
handleSIGHUP()
void handleSIGHUP (int signal)
{
     std::cout << "Caught signal " << signal << std::endl;
     if (WindowManager::getInstance() != nullptr) {
         WindowManager::getInstance()->Stop();
     }
 }
References WindowManager::getInstance(), and WindowManager::Stop().
Referenced by WindowManager::init().