YggdrasilWM: Client Class Reference
Client Class Reference
The Client class is responsible for managing the client windows. It creates a frame around the client window, Map the frame, Add the window to the save set, Reparent it, grab the buttons It also unframe the client window by removing the frame and reparenting the window to the root window It also move, resize, restack the client window.
#include <Client.hpp>
Public Member Functions
Client (Display *display, Window root, Window window, TreeLayoutManager *layout_manager, unsigned long InActiveColor, int BorderSize)
Client constructor.get window class and title.
~Client ()
Client destructor Destroy the Client object & the Frame Window it needed.
Client_Err frame ()
Client::frame create a frame around the client window, Map the frame, Add the window to the save set Reparent it, grab the buttons.
Client_Err unframe ()
Client::unframe unframe the client window by removing the frame and reparenting the window to the root window.
Window getWindow () const
Client::getWindow return the window attribute of the client.
void move (int x, int y)
: Client::move move the client window to the given position
void resize (int width, int height)
Client::resize resize the client window to the given size.
bool isFramed () const
Client::isFramed() check if the client is framed.
void setMapped (bool mapped)
Client::setMapped() set the mapped status of the client.
bool isMapped () const
Client::isMapped() check if the client is mapped.
const std::string & getTitle () const
Client::getTitle() return the title of the client, the title is get during the construction of the client.
const std::string & getClass () const
Client::getClass() return the class of the client, the class is get during the construction of the client.
Window getFrame () const
Client::getFrame() return the frame Window of the client.
void restack ()
Client::restack() restack the client window to avoid the frame to get in front of the client.
Static Public Member Functions
static std::string getError (Client_Err error)
Client::getError Return a string from an error of Client_Err enum.
Private Attributes
Display * display_
TreeLayoutManager * layout_manager_
Window root_
Window window_
Window frame_
unsigned int border_width
unsigned long border_color
bool framed
bool mapped {}
std::string title_
std::string class_
Detailed Description
The Client class is responsible for managing the client windows. It creates a frame around the client window, Map the frame, Add the window to the save set, Reparent it, grab the buttons It also unframe the client window by removing the frame and reparenting the window to the root window It also move, resize, restack the client window.
Constructor & Destructor Documentation
Client()
Client::Client (Display * display, Window root, Window window, TreeLayoutManager * layout_manager, unsigned long InActiveColor, int BorderSize)
Client constructor.get window class and title.
Parameters
display X11 display
root root window
window window to manage
layout_manager Reference to the layout manager
InActiveColor color of the border
BorderSize size of the border
        : display_(display),
          layout_manager_(layout_manager),
          root_(root),
          window_(window),
          frame_(0),
          border_width(BorderSize),
          border_color(InActiveColor),
          framed(false),
          mapped(false)
{
    Atom wmClassAtom = XInternAtom(display, "WM_CLASS", False);
    if (wmClassAtom == None) {
        std::cerr << "Failed to intern WM_CLASS atom." << std::endl;
    }
    Atom actualType;
    int actualFormat;
    unsigned long nItems, bytesAfter;
    unsigned char* propData;
    if (XGetWindowProperty(display, window, wmClassAtom, 0, 1024, False, AnyPropertyType,
                           &actualType, &actualFormat, &nItems, &bytesAfter, &propData) != Success) {
        std::cerr << "Failed to get WM_CLASS property." << std::endl;
    }
    Atom XA_STRING = XInternAtom(display, "STRING", False);
    if (actualType == XA_STRING && actualFormat == 8 && nItems > 1) {
        // The WM_CLASS property contains two null-terminated strings.
        char* instanceName = reinterpret_cast<char*>(propData);
        char* className = instanceName + strlen(instanceName) + 1;
        this->class_ = className;
        this->title_ = instanceName;
    } else {
        std::cerr << "Unexpected format or size of WM_CLASS property." << std::endl;
    }
    XFree(propData);
}
References class_, and title_.
~Client()
Client::~Client ()
Client destructor Destroy the Client object & the Frame Window it needed.
                {
    if (this->framed) {
        XDestroyWindow(display_, frame_);
    }
    std::cerr << "Client destroyed :" << title_ << std::endl;
}
References display_, frame_, framed, and title_.
Member Function Documentation
frame()
Client_Err Client::frame ()
Client::frame create a frame around the client window, Map the frame, Add the window to the save set Reparent it, grab the buttons.
{
    const unsigned long BG_COLOR = 0x000000;
    if (this->framed)
        return(YGG_CLI_LOG_ALREADY_FRAMED);
    XWindowAttributes x_window_attrs;
    if (XGetWindowAttributes(display_, window_, &x_window_attrs) == 0)
        return (YGG_CLI_ERR_RETRIEVE_ATTR);
    if (x_window_attrs.override_redirect)
        return(YGG_CLI_LOG_IGNORED_OVERRIDE_REDIRECT);
    this->frame_ = XCreateSimpleWindow(
            display_,
            root_,
            x_window_attrs.x,
            x_window_attrs.y,
            x_window_attrs.width,
            x_window_attrs.height,
            border_width,
            border_color,
            BG_COLOR
            );
        XSelectInput(
            display_,
            this->frame_,
            SubstructureRedirectMask | SubstructureNotifyMask | FocusChangeMask);
    XAddToSaveSet(display_,window_);
    XReparentWindow(
            display_,
            window_,
            frame_,
            0,0
            );
    XMapWindow(display_,frame_);
    // 9. Grab universal window management actions on client window.
    //   a. Move windows with alt + left button.
    XGrabButton(
            display_,
            Button1,
            Mod1Mask,
            window_,
            false,
            ButtonPressMask | ButtonReleaseMask | ButtonMotionMask,
            GrabModeAsync,
            GrabModeAsync,
            None,
            None);
    //   b. Resize windows with alt + right button.
//  XGrabButton(
//          display_,
//          Button3,
//          Mod1Mask,
//          window_,
//          false,
//          ButtonPressMask | ButtonReleaseMask | ButtonMotionMask,
//          GrabModeAsync,
//          GrabModeAsync,
//          None,
//          None);
    //   c. Kill windows with alt + f4.
    XGrabKey(
            display_,
            XKeysymToKeycode(display_, XK_F4),
            Mod1Mask,
            window_,
            false,
            GrabModeAsync,
            GrabModeAsync);
    //   d. Switch windows with alt + tab.
    XGrabKey(
            display_,
            XKeysymToKeycode(display_, XK_Tab),
            Mod1Mask,
            window_,
            false,
            GrabModeAsync,
            GrabModeAsync);
    this->framed = true;
    this->layout_manager_->addClient(this);
    return YGG_CLI_NO_ERROR;
}
References TreeLayoutManager::addClient(), border_color, border_width, display_, frame_, framed, layout_manager_, root_, window_, YGG_CLI_ERR_RETRIEVE_ATTR, YGG_CLI_LOG_ALREADY_FRAMED, YGG_CLI_LOG_IGNORED_OVERRIDE_REDIRECT, and YGG_CLI_NO_ERROR.
Referenced by WindowManager::getTopLevelWindows(), and EventHandler::handleMapRequest().
getClass()
const std::string & Client::getClass () const
Client::getClass() return the class of the client, the class is get during the construction of the client.
Returns
{ return class_; }
References class_.
getError()
static std::string Client::getError (Client_Err error) static
Client::getError Return a string from an error of Client_Err enum.
Parameters
error error code from the Client_Err enum
Returns
String of error
{
    switch (error) {
        case YGG_CLI_LOG_IGNORED_OVERRIDE_REDIRECT:
            return "Client::Frame ignoring window with override redirect attribute.";
        case YGG_CLI_LOG_ALREADY_FRAMED :
            return "Client::Frame Client has already been framed";
        case YGG_CLI_ERR_RETRIEVE_ATTR:
            return "Client could not retrieve Window Attributes";
        case YGG_CLI_LOG_IGNORE_NOT_FRAMED:
            return"Client::unFrame Client has no frame";
        default:
            return "Unknown error from Client Class";
    }
}
References YGG_CLI_ERR_RETRIEVE_ATTR, YGG_CLI_LOG_ALREADY_FRAMED, YGG_CLI_LOG_IGNORE_NOT_FRAMED, and YGG_CLI_LOG_IGNORED_OVERRIDE_REDIRECT.
Referenced by WindowManager::getTopLevelWindows().
getFrame()
Window Client::getFrame () const
Client::getFrame() return the frame Window of the client.
Returns
Window (frame)
{return frame_; }
References frame_.
Referenced by EventHandler::handleButtonPress(), EventHandler::handleFocusIn(), EventHandler::handleFocusOut(), EventHandler::handleMapNotify(), and EventHandler::handleMotionNotify().
getTitle()
const std::string & Client::getTitle () const
Client::getTitle() return the title of the client, the title is get during the construction of the client.
Returns
std::string
{ return title_; }
References title_.
Referenced by WindowManager::getTopLevelWindows(), EventHandler::handleFocusIn(), EventHandler::handleFocusOut(), EventHandler::handleMapNotify(), EventHandler::handleMapRequest(), EventHandler::handleUnmapNotify(), and WindowManager::insertClient().
getWindow()
Window Client::getWindow () const
Client::getWindow return the window attribute of the client.
Returns
Window
{
    return this->window_;
}
References window_.
Referenced by WindowManager::getTopLevelWindows(), and WindowManager::setFocus().
isFramed()
bool Client::isFramed () const
Client::isFramed() check if the client is framed.
Returns
{   return framed; }
References framed.
Referenced by EventHandler::handleMapRequest().
isMapped()
bool Client::isMapped () const
Client::isMapped() check if the client is mapped.
Returns
bool
{ return mapped; }
References mapped.
Referenced by EventHandler::handleMapRequest().
move()
void Client::move (int x, int y)
: Client::move move the client window to the given position
Parameters
x
y
{
    if (this->framed) {
        XMoveWindow(display_, frame_, x, y);
    }
    else {
        XMoveWindow(display_, window_, x, y);
    }
}
References display_, frame_, framed, and window_.
Referenced by TreeLayoutManager::placeClientInSpace().
resize()
void Client::resize (int width, int height)
Client::resize resize the client window to the given size.
Parameters
width
height
{
    if (this->framed) {
        XResizeWindow(display_, frame_, width, height);
    }
    XResizeWindow(display_, window_, width , height );
}
References display_, frame_, framed, and window_.
Referenced by TreeLayoutManager::growSpaceX(), and TreeLayoutManager::placeClientInSpace().
restack()
void Client::restack ()
Client::restack() restack the client window to avoid the frame to get in front of the client.
                     {
    if (this->framed) {
        XRaiseWindow(display_, frame_);
    }
    XRaiseWindow(display_, window_);
}
References display_, frame_, framed, and window_.
Referenced by EventHandler::handleMapNotify(), and TreeLayoutManager::placeClientInSpace().
setMapped()
void Client::setMapped (bool mapped)
Client::setMapped() set the mapped status of the client.
Parameters
mapped
Todo:
: update Mapped status in EventHandler Class
{ Client::mapped = m; }
References mapped.
Referenced by EventHandler::handleMapNotify().
unframe()
Client_Err Client::unframe ()
Client::unframe unframe the client window by removing the frame and reparenting the window to the root window.
Returns
Client_Err error code from the Client_Err enum
{
    if (!this->framed)
        return(YGG_CLI_LOG_IGNORE_NOT_FRAMED);
    XDestroyWindow(display_,frame_);
    this->framed = false;
    this->frame_ = 0;
    return YGG_CLI_NO_ERROR;
}
References display_, frame_, framed, YGG_CLI_LOG_IGNORE_NOT_FRAMED, and YGG_CLI_NO_ERROR.
Referenced by EventHandler::handleUnmapNotify().
Member Data Documentation
border_color
unsigned long Client::border_color private
Referenced by frame().
border_width
unsigned int Client::border_width private
Referenced by frame().
class_
std::string Client::class_ private
Referenced by Client(), and getClass().
display_
Display* Client::display_ private
Referenced by frame(), move(), resize(), restack(), unframe(), and ~Client().
frame_
Window Client::frame_ private
Referenced by frame(), getFrame(), move(), resize(), restack(), unframe(), and ~Client().
framed
bool Client::framed private
Referenced by frame(), isFramed(), move(), resize(), restack(), unframe(), and ~Client().
layout_manager_
TreeLayoutManager* Client::layout_manager_ private
Referenced by frame().
mapped
bool Client::mapped {} private
{};
Referenced by isMapped(), and setMapped().
root_
Window Client::root_ private
Referenced by frame().
title_
std::string Client::title_ private
Referenced by Client(), getTitle(), and ~Client().
window_
Window Client::window_ private
Referenced by frame(), getWindow(), move(), resize(), and restack().
The documentation for this class was generated from the following files:
inc/Client.hpp
src/Client.cpp