YggdrasilWM: Grow Class Reference
Grow Class Reference
Grow a window.
#include <Grow.hpp>
Public Member Functions
Grow ()
~Grow () override=default
void execute (const std::string &args) override
Each child class must implement this interface.
Static Public Member Functions
static DeserializedXKeyEvent deserializeXKeyEvent (const std::string &serializedEvent)
Detailed Description
Grow a window.
Constructor & Destructor Documentation
Grow()
Grow::Grow ()
            {
 }
~Grow()
Grow::~Grow () override default
Member Function Documentation
deserializeXKeyEvent()
DeserializedXKeyEvent Grow::deserializeXKeyEvent (const std::string & serializedEvent) static
{
     DeserializedXKeyEvent event;
     std::istringstream ss(serializedEvent);
     std::string item;
     // Extract args_
     std::getline(ss, item, ',');
     event.inc = std::stoi(item);
     // Extract subwindow
     std::getline(ss, item, ',');
     event.subwindow = static_cast<Window>(std::stoul(item));
     // Extract window
     std::getline(ss, item, ',');
     event.window = static_cast<Window>(std::stoul(item));
     // Extract state
     std::getline(ss, item, ',');
     event.state = std::stoul(item);
     // Extract keycode
     std::getline(ss, item, ',');
     event.keycode = std::stoul(item);
     return event;
 }
Referenced by execute().
execute()
void Grow::execute (const std::string & args) override virtual
Each child class must implement this interface.
Parameters
args arguments to the command
Implements CommandBase.
{
     WindowManager *wm = WindowManager::getInstance();
     DeserializedXKeyEvent event = deserializeXKeyEvent(args);
     std::shared_ptr<Client> client = wm->getClient(event.subwindow);
     if (client) {
         LayoutManager * lm = wm->getActiveGroup()->getLayoutManager().get();
         TreeLayoutManager * tlm = dynamic_cast<TreeLayoutManager *>(lm);
         if (tlm) {
             tlm->growSpace(client.get(), event.inc);
         }
     }
 }
References deserializeXKeyEvent(), WindowManager::getActiveGroup(), WindowManager::getClient(), WindowManager::getInstance(), and TreeLayoutManager::growSpace().
The documentation for this class was generated from the following files:
inc/Commands/Grow.hpp
src/Commands/Grow.cpp