YggdrasilWM: BinarySpace Class Reference
BinarySpace Class Reference
BinarySpace class This class represents a space in the layout. it's designed like a binary tree, with a parent, a right and a left child. Only leaf spaces have clients.
#include <BinarySpace.hpp>
Public Member Functions
BinarySpace (Point pos, Point size, int index, BinarySpace *parent=nullptr)
Construct a new BinarySpace object.
~BinarySpace ()=default
const Point & getPos () const
void setPos (const Point &pos)
const Point & getSize () const
void setSize (const Point &size)
int getSubspaceCount () const
int getIndex () const
void setIndex (int index)
BinarySpace * getParent () const
void setParent (BinarySpace *parent)
const std::unique_ptr< BinarySpace > & getRight () const
void setRight (std::unique_ptr< BinarySpace > right)
const std::unique_ptr< BinarySpace > & getLeft () const
void setLeft (std::unique_ptr< BinarySpace > left)
std::shared_ptr< Client > getClient () const
void setClient (std::shared_ptr< Client > client)
void incSubSpaceCount ()
Private Attributes
Point pos_
Point size_
int index_
int subspace_count_
BinarySpace * parent_
std::unique_ptr< BinarySpace > right_
std::unique_ptr< BinarySpace > left_
std::weak_ptr< Client > client_
Detailed Description
BinarySpace class This class represents a space in the layout. it's designed like a binary tree, with a parent, a right and a left child. Only leaf spaces have clients.
Todo:
create an interface for Spaces and implement it in BinarySpace
redefine BinarySpace not as a nested class but as a separate class
Constructor & Destructor Documentation
BinarySpace()
BinarySpace::BinarySpace (Point pos, Point size, int index, BinarySpace * parent = nullptr)
Construct a new BinarySpace object.
Parameters
pos
size
index
parent
                                               :
         pos_(pos),
         size_(size),
         index_(index),
         subspace_count_(1),
         parent_(parent),
         left_(nullptr),
         right_(nullptr){}
~BinarySpace()
BinarySpace::~BinarySpace () default
Member Function Documentation
getClient()
std::shared_ptr< Client > BinarySpace::getClient () const
{
     auto c = client_.lock();
     if (c)
         return c;
     else
         return nullptr;
 }
References client_.
Referenced by TreeLayoutManager::addClientRecursive(), TreeLayoutManager::findSpaceRecursive(), TreeLayoutManager::growSpace(), TreeLayoutManager::placeClientInSpace(), TreeLayoutManager::recursiveResize(), TreeLayoutManager::recursiveShrinkSiblingSpace(), TreeLayoutManager::removeClientRecursive(), and TreeLayoutManager::splitSpace().
getIndex()
int BinarySpace::getIndex () const
 { return index_; }
References index_.
getLeft()
const std::unique_ptr< BinarySpace > & BinarySpace::getLeft () const
 { return left_; }
References left_.
Referenced by TreeLayoutManager::addClientRecursive(), TreeLayoutManager::deleteSpace(), TreeLayoutManager::findSpaceRecursive(), TreeLayoutManager::growSpace(), TreeLayoutManager::recursiveResize(), TreeLayoutManager::recursiveShrinkSiblingSpace(), and TreeLayoutManager::removeClientRecursive().
getParent()
BinarySpace * BinarySpace::getParent () const
 { return parent_; }
References parent_.
Referenced by TreeLayoutManager::growSpace(), TreeLayoutManager::removeClientRecursive(), and TreeLayoutManager::splitSpace().
getPos()
const Point & BinarySpace::getPos () const
 { return pos_; }
References pos_.
Referenced by TreeLayoutManager::growSpace(), TreeLayoutManager::placeClientInSpace(), and TreeLayoutManager::splitSpace().
getRight()
const std::unique_ptr< BinarySpace > & BinarySpace::getRight () const
 { return right_; }
References right_.
Referenced by TreeLayoutManager::addClientRecursive(), TreeLayoutManager::deleteSpace(), TreeLayoutManager::findSpaceRecursive(), TreeLayoutManager::growSpace(), TreeLayoutManager::recursiveResize(), TreeLayoutManager::recursiveShrinkSiblingSpace(), and TreeLayoutManager::removeClientRecursive().
getSize()
const Point & BinarySpace::getSize () const
 { return size_; }
References size_.
Referenced by TreeLayoutManager::addClientRecursive(), TreeLayoutManager::growSpace(), TreeLayoutManager::placeClientInSpace(), TreeLayoutManager::recursiveResize(), TreeLayoutManager::recursiveShrinkSiblingSpace(), and TreeLayoutManager::splitSpace().
getSubspaceCount()
int BinarySpace::getSubspaceCount () const
 {return subspace_count_; }
References subspace_count_.
incSubSpaceCount()
void BinarySpace::incSubSpaceCount ()
 { subspace_count_ ++; }
References subspace_count_.
Referenced by TreeLayoutManager::splitSpace().
setClient()
void BinarySpace::setClient (std::shared_ptr< Client > client)
 { BinarySpace::client_ = std::weak_ptr<Client>(client); }
References client_.
Referenced by TreeLayoutManager::placeClientInSpace(), TreeLayoutManager::removeClientRecursive(), and TreeLayoutManager::splitSpace().
setIndex()
void BinarySpace::setIndex (int index)
 { BinarySpace::index_ = index; }
References index_.
setLeft()
void BinarySpace::setLeft (std::unique_ptr< BinarySpace > left)
 { this->left_ = std::move(left); }
References left_.
Referenced by TreeLayoutManager::removeClientRecursive(), and TreeLayoutManager::splitSpace().
setParent()
void BinarySpace::setParent (BinarySpace * parent)
 { BinarySpace::parent_ = parent;}
References parent_.
setPos()
void BinarySpace::setPos (const Point & pos)
 { BinarySpace::pos_ = pos; }
References pos_.
Referenced by TreeLayoutManager::growSpace(), and TreeLayoutManager::recursiveResize().
setRight()
void BinarySpace::setRight (std::unique_ptr< BinarySpace > right)
 { this->right_ = std::move(right); }
References right_.
Referenced by TreeLayoutManager::removeClientRecursive(), and TreeLayoutManager::splitSpace().
setSize()
void BinarySpace::setSize (const Point & size)
 { BinarySpace::size_ = size; }
References size_.
Referenced by TreeLayoutManager::growSpace(), TreeLayoutManager::recursiveResize(), and TreeLayoutManager::recursiveShrinkSiblingSpace().
Member Data Documentation
client_
std::weak_ptr<Client> BinarySpace::client_ private
Referenced by getClient(), and setClient().
index_
int BinarySpace::index_ private
Referenced by getIndex(), and setIndex().
left_
std::unique_ptr<BinarySpace> BinarySpace::left_ private
Referenced by getLeft(), and setLeft().
parent_
BinarySpace* BinarySpace::parent_ private
Referenced by getParent(), and setParent().
pos_
Point BinarySpace::pos_ private
Referenced by getPos(), and setPos().
right_
std::unique_ptr<BinarySpace> BinarySpace::right_ private
Referenced by getRight(), and setRight().
size_
Point BinarySpace::size_ private
Referenced by getSize(), and setSize().
subspace_count_
int BinarySpace::subspace_count_ private
Referenced by getSubspaceCount(), and incSubSpaceCount().
The documentation for this class was generated from the following files:
inc/Layouts/BinarySpace.hpp
src/Layouts/BinarySpace.cpp