YggdrasilWM: ewmh Namespace Reference
ewmh Namespace Reference
ewmh namespace This namespace contains the EWMH related functions.
Functions
void initEwmh (Display *display, Window root)
register the supported EWMH atoms.
void handleMessage (XClientMessageEvent *event, Display *display, Window root)
void updateNumberOfDesktops (Display *display, Window root)
void updateDesktopGeometry (Display *display, Window root)
void updateActiveWindow (Display *display, Window root, Window activeWindow)
void updateWmProperties (Display *display, Window root)
Detailed Description
ewmh namespace This namespace contains the EWMH related functions.
Function Documentation
handleMessage()
void ewmh::handleMessage (XClientMessageEvent * event, Display * display, Window root)
{
         Atom wmName = XInternAtom(display, "_NET_WM_NAME", False);
         Atom wmDesktop = XInternAtom(display, "_NET_WM_DESKTOP", False);
         Atom activeWindow = XInternAtom(display, "_NET_ACTIVE_WINDOW",False);
         Atom numbersOfDesktops = XInternAtom(display, "_NET_NUMBER_OF_DESKTOPS",False);
         Atom wmState  = XInternAtom(display, "_NET_WM_STATE", False);
         Atom desktopGeometry = XInternAtom(display, "_NET_DESKTOP_GEOMETRY",False);
         if (wmName != None
             && wmDesktop != None
             && activeWindow != None
             && numbersOfDesktops != None
             && wmState != None
             && desktopGeometry != None){
             if (event->message_type == wmName) {
                 Logger::GetInstance()->Log("Received _NET_WM_NAME message", L_INFO);
                 // Handle _NET_WM_NAME
             } else if (event->message_type == wmDesktop) {
                 Logger::GetInstance()->Log("Received _NET_WM_DESKTOP message", L_INFO);
                 // Handle _NET_WM_DESKTOP
             } else if (event->message_type == activeWindow) {
                 Logger::GetInstance()->Log("Received _NET_ACTIVE_WINDOW message", L_INFO);
                 // Handle _NET_ACTIVE_WINDOW
             } else if (event->message_type == numbersOfDesktops) {
                 Logger::GetInstance()->Log("Received _NET_NUMBER_OF_DESKTOPS message", L_INFO);
             } else if (event->message_type == wmState) {
                 Logger::GetInstance()->Log("Received _NET_WM_STATE message", L_INFO);
                 // Handle _NET_WM_STATE
             } else {
                 Logger::GetInstance()->Log("Unknown message type: " + std::to_string(event->message_type), L_WARNING);
             }
         }
     }
References Logger::GetInstance(), L_INFO, L_WARNING, and Logger::Log().
Referenced by EventHandler::handleClientMessage().
initEwmh()
void ewmh::initEwmh (Display * display, Window root)
register the supported EWMH atoms.
Parameters
display must be opened before call to this function.
root root window the wm is managing (usually the default root window)
Todo:
add x11wrapper to the parameters
{
         Atom netSupported = XInternAtom(display, "_NET_SUPPORTED", False);
         std::vector<Atom> supportedAtoms = {
                 XInternAtom(display, "_NET_WM_NAME", False),
                 XInternAtom(display, "_NET_WM_DESKTOP", False),
                 XInternAtom(display, "_NET_ACTIVE_WINDOW",False),
                 XInternAtom(display, "_NET_NUMBER_OF_DESKTOPS",False),
                 XInternAtom(display, "_NET_WM_STATE",False),
                 XInternAtom(display, "_NET_DESKTOP_GEOMETRY",False)
                 // Add other supported atoms here
         };
         // Register _NET_SUPPORTED property
         XChangeProperty(
                 display,                        // Display
                 root,                           // Root window
                 netSupported,                    // Property to change
                 XA_ATOM,                         // Type of property
                 32,                              // Format of the property (32-bit)
                 PropModeReplace,                 // Replace existing property
                 reinterpret_cast<unsigned char*>(supportedAtoms.data()), // New value
                 supportedAtoms.size()            // Number of elements in the new value
         );
         XFlush(display);
         Logger::GetInstance()->Log("EWMH atoms registered", L_INFO);
     }
References Logger::GetInstance(), L_INFO, and Logger::Log().
Referenced by WindowManager::init().
updateActiveWindow()
void ewmh::updateActiveWindow (Display * display, Window root, Window activeWindow)
{
         Atom activeWindowAtom = XInternAtom(display, "_NET_ACTIVE_WINDOW",False);
         XChangeProperty(display,
                         root,
                         activeWindowAtom,
                         XA_WINDOW,
                         32,
                         PropModeReplace,
                         (unsigned char*)&activeWindow,
                         1);
     }
Referenced by EventHandler::handleFocusIn(), and EventHandler::handleFocusOut().
updateDesktopGeometry()
void ewmh::updateDesktopGeometry (Display * display, Window root)
{
         Atom desktopGeometry = XInternAtom(display, "_NET_DESKTOP_GEOMETRY", False);
         uint32_t size[2] = {static_cast<uint32_t>(WindowManager::getInstance()->getGeometryX()),
                                 static_cast<uint32_t>(WindowManager::getInstance()->getGeometryY())};
         Logger::GetInstance()->Log("Size registered :\t" + std::to_string(size[0]) + " x " + std::to_string(size[1]), L_INFO);
         XChangeProperty(display,
                         root,
                         desktopGeometry,
                         XA_CARDINAL,
                         32,
                         PropModeReplace,
                         (unsigned char*)(size),
                         2);
     }
References WindowManager::getGeometryX(), WindowManager::getGeometryY(), Logger::GetInstance(), WindowManager::getInstance(), L_INFO, and Logger::Log().
Referenced by updateWmProperties().
updateNumberOfDesktops()
void ewmh::updateNumberOfDesktops (Display * display, Window root)
{
         Atom numbersOfDesktops = XInternAtom(display, "_NET_NUMBER_OF_DESKTOPS",False);
         if (numbersOfDesktops != None) {
             unsigned int n = WindowManager::getInstance()->getGroups().size();
             XChangeProperty(display, root, numbersOfDesktops, XA_CARDINAL, 32, PropModeReplace,reinterpret_cast<unsigned char*>(&n), 1);
         }
     }
References WindowManager::getGroups(), and WindowManager::getInstance().
Referenced by updateWmProperties().
updateWmProperties()
void ewmh::updateWmProperties (Display * display, Window root)
{
         updateNumberOfDesktops(display, root);
         updateDesktopGeometry(display,root);
     }
References updateDesktopGeometry(), and updateNumberOfDesktops().
Referenced by WindowManager::init().