name: Generate and Deploy Doxygen Documentation

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch. Adjust if your development branch is different.

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all history for .GitInfo and .NoJekyll support

    - name: Set up Doxygen
      uses: marketplace/actions/install-doxygen

    - name: Generate Doxygen Documentation
      run: |
        doxygen doxygen.cfg

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: doc/html # The folder the action should deploy.
        clean: true # Automatically remove all files from the deployment branch that are not present in the deployed folder.
        single-commit: true # Keep the deployment branch history clean with a single commit.
        commit-message: "Deploy Doxygen Documentation"

    # Optional: Add a step to copy the index.html at the root of the repo into the doc/html folder before deployment if needed.

