name: Generate and Deploy Doxygen Documentation

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch. Adjust if your development branch is different.

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz 

    - name: Generate Doxygen Documentation
      run: |
        doxygen doxygen.cfg

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: doc/html # The folder the action should deploy.
        clean: true # Automatically remove all files from the deployment branch that are not present in the deployed folder.
        single-commit: true # Keep the deployment branch history clean with a single commit.
        commit-message: "Deploy Doxygen Documentation"
        token: ${{ secrets.ACTION_PAT_V1 }}
